project:
  type: website
  output-dir: docs
  preview: 
    port: 4326
    browser: false

website:
  title: "biscotty's Workshop"
  favicon: images/BWLogo.png
  page-navigation: true
  back-to-top-navigation: true
  site-url: https://biscotty.online
  description: "For the love of learning"
  bread-crumbs: false
  open-graph: 
    site-name: biscotty's Workshop
    image: images/trunks.png
  navbar:
    right:
      - sidebar:posts-side
      - href: resources.qmd
        text: Resources
      # - href: documents/gpwh.pdf
      #   text: Article
      #   target: _blank
      - icon: github
        href: https://github.com/biscotty666
      - icon: rss
        href: blogs.xml
    left: 
      - text: "Home"
        href: index.qmd
      - href: about.qmd
        text: "About"
      - href: obsidian.qmd
        text: "Obsidian"
      - href: data-science.qmd
        text: "Data Science"        
      - href: blogs.qmd
        text: "All"
  page-footer: 
    background: dark
    left: Copyright 2025, Brian Carey
    right: This website is built with {{< fa heart title="a heart" >}}, [{{< fa brands github title="GitHub octocat logo" >}}](https://github.com/samanthacsik/samanthacsik.github.io){target=_blank}, [{{< fa brands r-project title="R Project" >}}](https://www.r-project.org/about.html){target=_blank} and [Quarto](https://quarto.org/){target=_blank}
  sidebar: 
    title: "Posts"
    id: posts-side
    style: "docked"
    search: true
    contents: 
      - data-science.qmd
      - obsidian.qmd
      - blogs/dataview.qmd
      - blogs/freeing-your-thinking.qmd
      - auto: blogs/data-science
      - auto: blogs/obsidian

  comments: 
    utterances: 
      repo: biscotty666/bw-comments

format:
  html:
    theme:
      light: 
        - litera
        - styles.scss
      dark: 
        - superhero
    mainfont: Nunito
    toc: true
    page-layout: full

editor: visual

