project:
  type: website
  output-dir: docs
  preview: 
    port: 4326
    browser: false

execute: 
  freeze: auto
  
website:
  title: "biscotty's Workshop"
  favicon: images/BWLogo.png
  page-navigation: true
  back-to-top-navigation: true
  site-url: https://biscotty.online
  description: "For the love of learning"
  bread-crumbs: false
  search: 
    location: navbar
    type: overlay
  open-graph: 
    site-name: biscotty's Workshop
    image: images/trunks.png
  navbar:
    left: 
      - text: "Home"
        href: index.qmd
      - href: about.qmd
        text: "About"
      - text: "Technology"
        menu:
          - href: posts/obsidian/obsidian.qmd
            text: "Obsidian"
          - href: posts/data-science/data-science.qmd
            text: "Data Science" 
          - href: posts/linux/linux.qmd
            text: Linux
      - text: "Humanities"
        menu: 
          - href: posts/chinese-medicine/chinese-medicine.qmd
            text: Chinese Medicine
      - href: posts/posts.qmd
        text: "All posts"
    right:
      - href: resources.qmd
        text: Resources
      - href: cv/brian-carey.qmd
        text: CV
      - icon: github
        href: https://github.com/biscotty666
      - icon: rss
        href: posts/posts.xml

  page-footer: 
    background: dark
    left: Copyright 2025, Brian Carey
    right: powered by [Quarto](https://quarto.org/){target=_blank}, [{{< fa brands github title="GitHub octocat logo" >}}](https://github.com/biscotty666/biscottys-workshop){target=_blank}, [{{< fa brands r-project title="R Project" >}}](https://www.r-project.org/about.html){target=_blank}, [NixOS](https://nixos.org), [NGINX](https://nginx.org) 
    center: built with FOSS
    
  sidebar: 
    - title: "Posts"
      id: posts-side
      style: "docked"
      contents: 
        - posts/data-science/data-science.qmd
        - posts/linux/linux.qmd
        - posts/obsidian/obsidian.qmd
        - posts/obsidian/dataview.qmd
        - posts/obsidian/freeing-your-thinking.qmd
        - auto: posts/data-science
        - auto: posts/linux
        - auto: posts/obsidian
        - auto: posts/chinese-medicine

    - title: "CV"
      id: cv-side
      style: "docked"
      contents: 
        - cv/brian-carey.qmd
        - auto: cv/vignettes
      
  comments: 
    utterances: 
      repo: biscotty666/bw-comments

format:
  html:
    theme:
      light: 
        - litera
        - styles.scss
      dark: 
        - superhero
    mainfont: Nunito
    toc: true
    page-layout: full
    anchor-sections: true
    smooth-scroll: true
    link-external-icon: true
    link-external-newwindow: true
    image-lazy-loading: true

editor: visual

