---
title: "Managing Change"
description: "Motivating people in times of disruption"
date: 04-14-2025
categories: [Management]
draft: true
draft-mode: visible
format: html
---

I joined Autodesk's European Software Center in the course of a reorganization. Before that I had been the Sr. Financial Analyst in charge of budgeting and forecasting for the Center, which was responsible for all localization and internationalization activities for Europe, the Americas, and later Asia as well. As the finance partner for the organization I was closely involved in the planning of the reorganization.

The reorganization was meant to parallel a corporate-wide restructuring into market sectors, each with specific products, so it entailed assigning engineers to each group.  Translation work would be almost entirely outsourced, and engineering work maintained largely in-house, with supplemental engineers, primarily QA related, provided by external vendors as well. In the eventuality, only a skeleton crew of translators remained to cover the big four European languages.

In addition to managing all of the vendors, I was given the group of five translators and an administrative assistant. In the software industry, engineers are kings and queens, everyone else an afterthought. On a personal level, these were people who had had a "place" on assigned teams, and were now grouped together in a separate, bare-bones department with an ill-defined mission. Of course the laying off of many of their colleagues only exacerbated their emotional distress.

I decided to make the translators into vendor managers for their languages.

My team was composed of translators, not vendor managers. The skills necessary for translation work are not the same as managing a group of translators. The team needed to acquire these skills, and the opportunity to do so provided the motivation to be "all-in". I didn't lose a single employee.