---
title: "TCM Clinic"
subtitle: "Owned and operated a Chinese medicine clinic"
description: "While practicing as a Doctor of Oriental Medicine, I ran a clinic which offered acupuncture, massage, and herbal therapy which served private and insured patients."
date: 04-28-2025
categories: 
  - Financial
  - Management
  - Chinese Medicine
format: html
---

---

# Introduction

For most of the 20 years I practiced Chinese Medicine, I owned and operated a private clinic which served around 40 clients per week. As a Doctor of Oriental Medicine, I administered both acupuncture and herbal therapy. Therapeutic massage was also offered.

In New Mexico, acupuncture services are covered by many insurance plans. I was a provider for the largest insurance companies in the state, including Blue Cross, United and Presbyterian, and processed insurance claims for the majority of my clients.

# Conditions treated

Acupuncture is best known for pain syndromes, both acute and chronic. Unsurprisingly, a large percentage of my patients came for treatment of neck, shoulder and back pain, as well as headaches and menstrual pain. In most cases, these were chronic conditions associated with, for example, arthritis, migraines or pre-menstrual syndrome. 

Other health concerns I treated regularly included emotional issues such as insomnia, depression and anxiety, and digestive issues such as indigestion, reflux, diarrhea and constipation. Occasionally people would come for cold and flu treatment.

# Services

I practiced several styles of acupuncture. My formal training was in the style currently practiced in China referred to as Traditional Chinese Medicine (TCM), and I often used it for simple cases because it is efficient. I also trained in two Japanese styles, in particular that of Kiiko Matsumoto, which I used when TCM didn't produce adequate results, and the Taoist based style of Jeffrey Yuen, which I used primarily for emotional conditions.

My specialty was herbal medicine, which I taught for over 10 years at the local acupuncture college (SWAC). Designing precise formulas for complex conditions is difficult, and little practiced in the US among non-Chinese practitioners. I stocked over 100 herbs, many in powder form, which I used to prepare custom formulas for patients. In simple cases, I dispensed prepared pills and tablets, and many patients with body pain received topical medication as well.

I incorporated some massage in my treatments, but therapeutic massage services were primarily offered by Licensed Massage Therapists working at the clinic.
