---
title: "Trail Mapping with R"
output: html_document
date: "2025-03-30"
execute:
  cache: true
---

```{r setup, include=FALSE, paged.print=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Trail Mapping with R

```{r}
library(gpx)
library(sf)
library(tidyverse)
library(leaflet)
```

## Read in a file and inspect

```{r}
trek_data <- read_gpx("../../data/GPX/b3/Workout-2024-09-06-16-29-37.gpx")
str(trek_data)
```

```{r}
trek_tracks <- trek_data[[2]]
str(trek_tracks)
```

```{r}
trek <- trek_tracks[[1]]
head(trek)
```

## Importing a collection of treks

```{r}
files <- list.files(path = "../../data/GPX/b3", pattern = "\\.gpx$",
                    full.names = TRUE)
data_list <- list()
i = 1
for (file in files) {
  data <- read_gpx(file)[[2]][[1]]
  data$id = i
  i <- i + 1
  data_list[[file]] <- data
}
tracks_df <- bind_rows(data_list)
str(tracks_df)
```


```{r}
treks <- tracks_df |> 
  st_as_sf(coords = c("Longitude","Latitude"),
           crs = 4326)
trek <- treks[treks$id == 1,]
plot(trek["Elevation"])
```

```{r}
l <- leaflet(trek) |> 
  addTiles() |> 
  addCircles(color = "turquoise", fill = "None",
             opacity = 0.3, radius = 3) |> 
  addMiniMap()
l
```

```{r}
pal <- colorNumeric(palette = "viridis", domain = trek$Elevation)

leaflet() |> 
  addTiles() |> 
  addCircles(data = trek, color=pal(trek$Elevation), 
             opacity = 0.5, radius = 3)
```

```{r}
library(htmltools)

leaflet() |> 
  addTiles() |> 
  addCircles(data = trek, color=pal(trek$Elevation), 
             opacity = 0.5, radius = 3,
             label = ~htmlEscape(Elevation))
```

