---
title: High stakes negotiation
subtitle: Win-win is (almost) always possible
desription: Obtaining reparations without losing partnershipsI salvaged an important business relationship while obtaining significant compensation for poor performance.
date: 04-28-2025
categories: 
  - Financial
  - Management
toc: true
format: html
---

------------------------------------------------------------------------

As the Worldwide Vendor Manager for localization services at Autodesk, negotiation was a regular part of my job. My primary goals in that role were to control costs and cultivate vendors qualified to provide the services we require. By having an adequately large pool, competition made pricing negotiations pretty easy. On the other hand, when things go wrong on a project, negotiation becomes much more complex.

Here I will briefly describe a high-stakes negotiation I led, and then describe how I approached this difficult situation.

## Background

Autodesk was flying high after the twelfth release of its flagship product AutoCAD, which had reinforced its dominant position in the computer aided design space. I was working in Europe during the release of the subsequent R13. It was a pretty disastrous release cycle in many ways, beginning upstream, and upstream chaos multiplies downstream as the product is localized into multiple languages. Most of the localization work for Europe was done by a single vendor, which was one of the few large-scale vendors, operating out of London at the time.

After the project was over, the internal team wanted compensation, almost retribution. Clearly comependsation was due, although, on the facts and history, there was certainly an aspect of shared responsibility. I had only recently been instituted in the newly-created role of vendor manager, and was responsible for the negotiations. I had previously been the finance and administration partner to the software center, so I was already familiar with the financial aspects.

## Be prepared

There's no better tactic than having facts at your fingertips and being knowledgeable about the details of a situation, information which, often, those sitting across the table do not possess.

Preparation is the most important part of any negotiation, especially when emotions are running high. The internal situation must be understood, and the impact of internal chaos on the vendor must be recognized. The vendor's positions must be clarified in so far as possible, and an understanding of the internal dynamics of the vendor's company should be explored as well to predict their arguments and broader interests.

## Relative value

Negotiation is not a zero-sum game. There are aspects which can be clearly quantified, of course, which can only be awarded to one side, but there are other aspects to whose value is not so easily assigned a dollar amount. It is the latter which should preoccupy the negotiator, since it is there that a zero sum game can be turned into a win-win situation.

Where a value is not objective, it is subjective, and each party assigns a different value to each point in contention. Effort should be made to estimate the value that the other party places on each point. Whenever a point is conceded, there is an exchange of value. Things that are of low value to me but high value to my opponent are tactically very useful, they are the low-hanging fruit. Furthermore, one should consider bringing new issues to the table which are of low value to oneself but high value to the opponent, because these are powerful bargaining chips. Alternatively, if a point is of high value to me, yet I recognize it as low value for the opponent, I will not give over-large concessions.

## Internal homework

When a project goes poorly, it is natural to assign blame and holler for retribution. There are two parts to compensation: actual damages and punishment. In my opinion, punitive damages are normally not in the best interests of either party. As the saying goes "it's not personal, it's business."

I interviewed the department manager, project leads, engineers and translators involved in particularly problematic aspects of the project. This gave me the data I needed to establish a strong case, while sifting out the more emotional and CYA aspects of their complaints.

I considered my "internal customers" responsibility to be the director of the software center, who was my direct report, and the director of finance and administration for Europe. Of course, I also answered to the project teams who relied on me for the services they needed, and had my own interests, namely keeping an important resource available in the future.

At a management level, expectations for the outcome needed to be clearly laid out, both financial and non-tangible issues. In practice, this means agreeing on three outcomes: the ideal case, where you get everything you want, the walk-away point where the relationship is severed and lawyers get involved, and a reasonable and fair resolution that doesn't a bad taste in anyone's mouth.

## External homework

The better you understand the internal dynamics of your opponent, the better you can estimate the relative value of the issues on the table, and predict there positions and soft spots. Here it is useful to take a broader, industry-wide perspective. Our opponent was in fierce competition with a couple other large companies, with new, smaller, and less expensive vendors popping up all the time. We needed both types, and I did not want to lose one of the major suppliers, reducing competition for our contracts. Information can be gleaned from internal team members who developed strong relationships with their contacts at the vendors.

## In the room

If one is to quickly conclude a negotiation, of course, the principles must be in the room, which in my case were the two directors. I did not include the responsible department manager for most of the sessions, as I was well versed in the specific points and wanted to minimize personal, emotional expressions from our side. They brought their president, the manager of our account, and project manager. They needed the project manager because the account manager was not adequately conversant in the issues discussed, but his defensiveness impeded the negotiation.

My general approach was to emphasize the value of retaining the partnership between ourselves and the vendor, projecting the relationship as more valuable to them than us. We were a regular source of contracts, some quite large, in a highly competitive space. Successful negotiations meant future business.

On the other hand, they were one of the few full-service (engineers and translators), multi-lingual shops around. I needed to convince them that we had numerous other options, and that the on-going relationship was desirable, but not critical, to us. This was not entirely true, of course.

## The outcome

After a number of sessions, we got a refund of around a fourth of the contract value, nearer to our ideal goal than to our "expected" outcome. The other company received a commitment that they would be asked to bid for future projects and given fair consideration, as long as they accepted my new contract and bidding structure. In fact, they ended up being selected by the project team (and myself) as the primary vendor for the subsequent major release as well as some other, smaller projects.
