---
title: Food and the _qi_ of spring
subtitle: Chinese medicine food therapy
bibliography: ../../../references.bib
date: 05-10-2025
categories: [Chinese Medicine, Food]
---

The *Huáng dì nèi jīng* (黃帝內經) is the oldest extant Chinese medical text, and before addressing disease and its treatment, it discusses disease prevention: how to stay healthy. In fact, it states that those who maintain an appropriate diet and activity level, together with rest and relaxation, should rarely fall ill, and quickly recover when they do, with moderation necessary in all things. This seem somewhat obvious, but the *nèi jīng* adds, and emphasizes, another element, which may seem strange to Westerners: everything should be done in accordance with the season.

In practice, attention to the season is critical in treating patients. A fever in summer is, in nearly all respects, different from an fever in winter, with regard to etiology, pathology, treatment and prognosis. In day-to-day living, it is equally important to pay attention to the season, if one is to maintain maximal health.

It should be recognized that humans today have much less regular exposure to the progression of seasons than in the vast history of our evolution. Air conditioning and cars allow people to avoid being outside almost entirely, thus limiting their exposure to environmental conditions. Those who do not spend time outside, or otherwise expose themselves to seasonal changes, tend to be more subject to seasonal illnesses in my experience.

Spring is upon us, and in this article, I will explain how to maintain an optimal diet for the spring season, foods to seek out and to avoid, and end with some spring meal ideas.

# The *qi* of spring

The *nèi jīng* describes how to live in accordance with each season.

> "...the spring season brings about the revitalization of all things in nature. It is the time of birth. (...) During this season it is advisable to retire early. Arise early also and go walking in order to absorb the fresh, invigorating energy...\[O\]ne should attempt to correspond to it directly by being open and unsuppressed, both physically and emotionally. (...) \[E\]xercise more frequently..do stretching exercises to loosen up the tendons and muscles. Emotionally, it is good to develop equanimity. This is because spring is the season of the liver, and indulgence in anger, frustration, depression sadness, or any excess emotion can injure the liver."[@Ni_1995, pp. 5]

The exortation to exercise early is particularly valuable. Note the association with the Liver. Each organ system, of which there are five^[Liver, Kidney, Spleen, Lung, Heart], are associated with a season. Therapeutically, disorder in an organ system is most easily treated in its corresponding season. With regard to disease prevention and diet, foods should be chosen that promote the natural functioning of the Liver system.

# The Liver

Chinese medicine assigns to the _Liver System_ a range of anatomical structures and physiological functions far beyond that of the Liver organ. Anatomically, it includes the muscles, tendons and ligaments, psychologically it is an emotional regulator, in both cases ensuring free movement and flexibility. It is related to the eyes and responsible for vision. It has many other functions as well.

Disorders of the _Liver System_ 
Importantly from a dietary perspective, it ensures that the digestive

The _nàn jīng_ describes many aspects of the Liver system:

> "During spring, the subtlety and vastness of the universe, the intelligence and intention of the human being, the ability of the earth to produce the ten thousand things, the natural movement of the wind, and the upward motion of all plants, collectively produce the movement of the tendons, the color green, the shouting of the voice, the spasms and convlusions, the eys, the sour taste, and the angry emotions. These are all associated with the liver, since the liver is responsible for mantaining the patency of the flow of energy, and its nature is movement and expansion."

It also warns against the dangers particular to the Liver system:

> "Anger can injure the liver, but sadness can relieve anger. When wind invades with dampness, it can injure the tendons, although dryness may eliminate the dmapness and wind.\
> Excessive consumption of sour foods can mke the tendons flaccid, but this can be neutralized by the pungent taste."
>
> [@Ni_1995, pp. 20]



# Taste

> "In general, foods that are pungent have dispresing qualities, those that are sour have astringent qualities, sweet foods have harmonizing and decelerating qualities, bitter foods have a dispensing and drying effect, and salty foods have a softening effect."
>
> "The five grains are used to nourish, the five fruits to assist, the five animals to fortify, the five vegetables to fulfill. These five types of food have specific effects and properties."
>
> [@Ni_1995, pp. 94]

> "In the east, wind arises, there is movement that promotes green woody grouwth, and when unripe, gives off a sour taste. The sour taset stimulates the liver when ingested and nourishes the tendons and ligaments. When the wind is gentle it harmonizes all, but when it is extremem it can be destructive, just as in people, emotion turns into rage when the liver is out of control. Metal is the control element, so therefore grief counters anger while dryness lessens the wind and pungent neutralizes sour."
>
> [@Ni_1995, pp. 243]

# Recipes

Enjoyment of food is not only emotionally pleasing, but improves the absorption of the nutrition it contains. All flavors and colors are ideally included in any meal. Here I will give some ideas for some meals which are ideal for spring. They balance the pungent[^1] and the sour, while using foods that promote the upward energy[^2] appropriate for spring.

[^1]: Includes green onions, chives, parsley, coriander, but includes most every herb which thrives in the spring and all the onion family.[@Lu_1994]

[^2]: Such foods include apricots, beets, mushrooms, cabbach, carrot, celery, eggs, grapes, honey, kidney beans, milk, olives, peanuts, oysters, string beans, sweet potatoes, kohlrabi, figs.[@Lu_1994]

::: {.callout-note title="Don't forget the salt"}
Salt is necessary for the cooking process and critical for bringing out the flavor of food. In Asian foods, this is normally supplied by soy and/or fish sauce. In western foods, you must season food as you cook.
:::

## Salad

beetroot salad with peppermint vinegrette

## Soup

leek soup with chestnuts and grains

## Mains

stir-fry with celery, shitakke, and plum sauce

lime-cilantro shrimp

## Drink

Mint julep
