---
title: "Collaborative Forecasts"
subtitle: "Always on target"
description: "Fostering financial literacy among department heads so as not to miss opportunities, and never miss targets."
date: 04-14-2025
categories: 
 - Management
 - Technology
 - Financial
comments: false
draft: false
format: html
---

It was important to me that the department managers at Autodesk's European Operations and Software Center were closely involved in the budgeting and monthly forecasting, for which I was responsible. I had a number of goals, one being, of course, to always be on target. But beyond that, I wanted to make the entire process tangible to the managers, some of whom were savvy, but most of whom saw the process initially as a painful exercise distracting them from their "real work".

To that end, I provided an Excel workbook to each department head, and we created evebt-based budgets from the bottom up, listing all of the staffing changes and other specific expenditures that the manager intended for the year, ensuring of course that overall targets were met.

Each month, I was able to give each manager an updated version of their workbook, containing actuals with comparisons to both the budget and the most recent forecast. It was easy, then, to re-forecast each month, since the listed events either happened or were cancelled or delayed.

This way, I could also ensure that managers were aware of opportunities generated by the forecasts. As a simple example, a hire budgeted for in March, but not engaged until a month or so later, can free up significant funds for other expenditures which had been prohibited by budget constraints. 

Of course, it was my job also to ensure that money wasn't spent just because it was there, but that was rarely if ever a problem. This also allowed the directors to have a clear financial picture of all the departments, enabling them to make inter-departmental allocation decisions with regard to the "available" funds.